/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#6c5842',
        'primary-container': '#867159',
        'primary-fixed': '#fadec1',
        'primary-fixed-dim': '#dcc2a7',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#271907',
        secondary: '#5f5e5b',
        'secondary-container': '#e5e2dd',
        'on-secondary': '#ffffff',
        tertiary: '#68594a',
        'tertiary-container': '#827261',
        'on-tertiary': '#ffffff',
        background: '#fff8f5',
        'on-background': '#1e1b18',
        surface: '#fff8f5',
        'on-surface': '#1e1b18',
        'surface-variant': '#e9e1dc',
        'on-surface-variant': '#4e453d',
        'surface-container': '#f5ece7',
        'surface-container-low': '#fbf2ed',
        'surface-container-high': '#efe6e2',
        'surface-container-highest': '#e9e1dc',
        'outline': '#7f756c',
        'outline-variant': '#d1c4ba',
        'inverse-surface': '#34302c',
        'inverse-on-surface': '#f8efea',
        'inverse-primary': '#dcc2a7',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['"Noto Serif"', 'serif'],
        luxury: ['"Playfair Display"', 'serif'],
      },
      fontSize: {
        'display': ['56px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '300' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '300' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      animation: {
        'fade-up': 'fadeUp 0.7s ease forwards',
        'fade-in': 'fadeIn 1s ease forwards',
        'bounce-slow': 'bounce 2s infinite',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
